[tasks.stage-all]
command = "git"
args = ["add", "-A"]

[tasks.commit]
command = "git"
args = ["commit", "-m", "update content"]

[tasks.push]
command = "git"
args = ["push", "-u", "origin", "master"]

[tasks.update-content]
dependencies = [
    "stage-all",
    "commit",
    "push"
]
